<?php

return [
    'enabled' => env('SYNC_ENABLED', false),
    'mode' => env('SYNC_MODE', 'standalone'),
    'remote_url' => rtrim((string) env('SYNC_REMOTE_URL', ''), '/'),
    'device_uuid' => env('SYNC_DEVICE_UUID'),
    'device_secret' => env('SYNC_DEVICE_SECRET'),
    'batch_size' => max(10, (int) env('SYNC_BATCH_SIZE', 100)),
    'lease_hours' => max(1, (int) env('SYNC_LEASE_HOURS', 72)),
    'request_timeout' => max(5, (int) env('SYNC_REQUEST_TIMEOUT', 45)),
    'protocol_version' => 1,

    // Parent records appear before their children. Cyclic nullable references are
    // deferred by the apply service and repaired after the batch is complete.
    'tables' => [
        'permissions',
        'roles',
        'users',
        'system_settings',
        'payment_methods',
        'financial_categories',
        'customer_charge_types',
        'authorities',
        'service_areas',
        'service_area_mosques',
        'departments',
        'job_positions',
        'work_shifts',
        'public_holidays',
        'leave_policies',
        'payroll_deduction_rules',
        'shareholders',
        'suppliers',
        'goods',
        'warehouses',
        'accounting_accounts',
        'customers',
        'employees',
        'billing_periods',
        'customer_contracts',
        'meters',
        'meter_assignments',
        'meter_seals',
        'meter_movements',
        'meter_readings',
        'invoices',
        'invoice_items',
        'payments',
        'payment_allocations',
        'customer_deposits',
        'customer_deposit_allocations',
        'customer_documents',
        'customer_charges',
        'customer_service_requests',
        'customer_connection_events',
        'accounting_transactions',
        'inventory_items',
        'inventory_transactions',
        'inventory_requests',
        'inventory_request_items',
        'inventory_purchase_payments',
        'inventory_issues',
        'inventory_issue_items',
        'asset_purchases',
        'assets',
        'asset_maintenance',
        'employee_documents',
        'employee_leave_balances',
        'employee_shift_assignments',
        'employee_payroll_deductions',
        'attendance_records',
        'leave_requests',
        'salary_advances',
        'employee_adjustments',
        'performance_reviews',
        'payroll_runs',
        'payroll_items',
        'payroll_advance_allocations',
        'payroll_deduction_allocations',
        'employee_terminations',
        'termination_advance_allocations',
        'biometric_import_batches',
        'account_reconciliations',
        'account_reconciliation_items',
        'financial_period_closings',
        'shareholder_distributions',
        'shareholder_distribution_items',
        'shareholder_payments',
        'supplier_purchase_contracts',
        'supplier_installments',
        'contract_cancellation_requests',
        'contract_cancellation_items',
    ],

    'files' => [
        'customers' => ['photo_path' => 'local'],
        'customer_documents' => ['path' => 'local'],
        'meter_seals' => ['photo_path' => 'local'],
        'accounting_transactions' => ['attachment_path' => 'public'],
        'supplier_purchase_contracts' => ['attachment_path' => 'public'],
        'employee_documents' => ['path' => 'public'],
        'leave_requests' => ['attachment_path' => 'public'],
        'asset_purchases' => ['attachment_path' => 'public'],
        'biometric_import_batches' => ['file_path' => 'local'],
    ],

    'ignored_columns' => [
        'users' => ['remember_token', 'last_login_at'],
    ],

    // These references are intentionally polymorphic and therefore do not have
    // database foreign keys. Their numeric IDs are translated through the same
    // stable entity UUIDs used for ordinary relationships.
    'indirect_references' => [
        'invoices' => [
            'type_column' => 'source_type',
            'id_column' => 'source_id',
            'types' => [
                'customer_charge' => 'customer_charges',
                'customer_contract' => 'customer_contracts',
                'inventory_request' => 'inventory_requests',
                'meter_reading' => 'meter_readings',
            ],
        ],
        'accounting_transactions' => [
            'type_column' => 'source_type',
            'id_column' => 'source_id',
            'types' => [
                'asset_purchase' => 'asset_purchases',
                'customer_contract_payment_allocation' => 'payment_allocations',
                'customer_deposit' => 'customer_deposits',
                'customer_deposit_application' => 'customer_deposit_allocations',
                'customer_deposit_refund' => 'customer_deposits',
                'customer_payment' => 'payments',
                'customer_payment_allocation' => 'payment_allocations',
                'customer_payment_allocation_refund' => 'payment_allocations',
                'customer_payment_refund' => 'payments',
                'employee_termination' => 'employee_terminations',
                'inventory_purchase_payment' => 'inventory_purchase_payments',
                'inventory_request' => 'inventory_requests',
                'inventory_request_cogs' => 'inventory_requests',
                'payroll_run' => 'payroll_runs',
                'salary_advance' => 'salary_advances',
                'shareholder_payment' => 'shareholder_payments',
                'supplier_installment' => 'supplier_installments',
            ],
        ],
        'inventory_transactions' => [
            'type_column' => 'reference_type',
            'id_column' => 'reference_id',
            'model_types' => true,
            'types' => [],
        ],
    ],

    // Framework/runtime data is deliberately local to each installation.
    // Permission pivots are carried as virtual fields on users and roles.
    'excluded_tables' => [
        'cache',
        'cache_locks',
        'failed_jobs',
        'jobs',
        'job_batches',
        'migrations',
        'model_has_permissions',
        'model_has_roles',
        'notifications',
        'password_reset_tokens',
        'personal_access_tokens',
        'role_has_permissions',
        'sessions',
        'sync_changes',
        'sync_conflicts',
        'sync_deferred_relations',
        'sync_devices',
        'sync_entities',
        'sync_node_states',
        'sync_runs',
    ],
];
