<?php

use App\Http\Controllers\Api\AccountingController;
use App\Http\Controllers\Api\AccountReconciliationController;
use App\Http\Controllers\Api\AssetController;
use App\Http\Controllers\Api\AssetMaintenanceController;
use App\Http\Controllers\Api\AssetPurchaseController;
use App\Http\Controllers\Api\AttendanceController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AuthorityController;
use App\Http\Controllers\Api\BillingPeriodController;
use App\Http\Controllers\Api\BiometricAttendanceController;
use App\Http\Controllers\Api\CustomerChargeTypeController;
use App\Http\Controllers\Api\CustomerContractController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\CustomerDepositController;
use App\Http\Controllers\Api\CustomerDocumentController;
use App\Http\Controllers\Api\CustomerOperationsController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\EmployeeAdjustmentController;
use App\Http\Controllers\Api\EmployeeController;
use App\Http\Controllers\Api\EmployeeDocumentController;
use App\Http\Controllers\Api\EmployeeTerminationController;
use App\Http\Controllers\Api\FinancialCategoryController;
use App\Http\Controllers\Api\FinancialPeriodClosingController;
use App\Http\Controllers\Api\FinancialReportController;
use App\Http\Controllers\Api\GoodController;
use App\Http\Controllers\Api\HrStructureController;
use App\Http\Controllers\Api\InventoryController;
use App\Http\Controllers\Api\InventoryIssueController;
use App\Http\Controllers\Api\InventoryRequestController;
use App\Http\Controllers\Api\InvoiceController;
use App\Http\Controllers\Api\LeavePolicyController;
use App\Http\Controllers\Api\LeaveRequestController;
use App\Http\Controllers\Api\LeaveSettingsController;
use App\Http\Controllers\Api\LocalSyncController;
use App\Http\Controllers\Api\MeterAssignmentController;
use App\Http\Controllers\Api\MeterController;
use App\Http\Controllers\Api\MeterReadingController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\OperationalReportController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\PaymentMethodController;
use App\Http\Controllers\Api\PayrollController;
use App\Http\Controllers\Api\PayrollDeductionController;
use App\Http\Controllers\Api\PayrollReportController;
use App\Http\Controllers\Api\PerformanceReviewController;
use App\Http\Controllers\Api\RoleController;
use App\Http\Controllers\Api\RemoteSyncController;
use App\Http\Controllers\Api\SalaryAdvanceController;
use App\Http\Controllers\Api\ServiceAreaController;
use App\Http\Controllers\Api\SettingController;
use App\Http\Controllers\Api\ShareholderController;
use App\Http\Controllers\Api\ShareholderDistributionController;
use App\Http\Controllers\Api\SupplierController;
use App\Http\Controllers\Api\SyncDeviceController;
use App\Http\Controllers\Api\TrainingModeController;
use App\Http\Controllers\Api\UserController;
use App\Http\Controllers\Api\WorkScheduleController;
use Illuminate\Support\Facades\Route;

Route::post('auth/login', [AuthController::class, 'login']);

Route::prefix('sync/remote')->middleware('sync.device')->group(function (): void {
    Route::get('handshake', [RemoteSyncController::class, 'handshake']);
    Route::post('push', [RemoteSyncController::class, 'push']);
    Route::get('pull', [RemoteSyncController::class, 'pull']);
    Route::get('manifest', [RemoteSyncController::class, 'manifest']);
    Route::post('file', [RemoteSyncController::class, 'uploadFile']);
    Route::get('file', [RemoteSyncController::class, 'downloadFile']);
    Route::post('lease/acquire', [RemoteSyncController::class, 'acquireLease']);
    Route::post('lease/release', [RemoteSyncController::class, 'releaseLease']);
});

Route::middleware('auth:sanctum')->group(function (): void {
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::put('auth/profile', [AuthController::class, 'updateProfile']);
    Route::post('auth/logout', [AuthController::class, 'logout']);

    Route::get('sync/status', [LocalSyncController::class, 'status']);
    Route::post('sync/runs', [LocalSyncController::class, 'start']);
    Route::post('sync/runs/{syncRun}/advance', [LocalSyncController::class, 'advance']);
    Route::post('sync/cloud-queue/repair', [LocalSyncController::class, 'repairCloudQueue']);
    Route::get('sync/conflicts', [LocalSyncController::class, 'conflicts']);
    Route::post('sync/conflicts/{syncConflict}/resolve', [LocalSyncController::class, 'resolve']);
    Route::post('sync/lease/acquire', [LocalSyncController::class, 'acquireLease']);
    Route::post('sync/lease/release', [LocalSyncController::class, 'releaseLease']);
    Route::get('sync/devices', [SyncDeviceController::class, 'index']);
    Route::post('sync/devices', [SyncDeviceController::class, 'store']);
    Route::post('sync/devices/{syncDevice}/rotate', [SyncDeviceController::class, 'rotate']);
    Route::delete('sync/devices/{syncDevice}', [SyncDeviceController::class, 'destroy']);

    Route::get('notifications', [NotificationController::class, 'index']);
    Route::post('notifications/read-all', [NotificationController::class, 'markAllRead']);
    Route::post('notifications/{notification}/read', [NotificationController::class, 'markRead']);

    Route::get('dashboard/stats', DashboardController::class);
    Route::apiResource('users', UserController::class);
    Route::apiResource('roles', RoleController::class);
    Route::get('settings', [SettingController::class, 'index']);
    Route::put('settings/system-profile', [SettingController::class, 'updateSystemProfile']);
    Route::get('training-mode', [TrainingModeController::class, 'show']);
    Route::put('settings/training-mode', [TrainingModeController::class, 'update']);
    Route::post('settings/training-mode/reset', [TrainingModeController::class, 'reset']);
    Route::post('settings/training-mode/reset/start', [TrainingModeController::class, 'startReset']);
    Route::post('settings/training-mode/reset/{operation}/advance', [TrainingModeController::class, 'advanceReset']);
    Route::get('settings/leave', [LeaveSettingsController::class, 'show']);
    Route::put('settings/leave', [LeaveSettingsController::class, 'update']);
    Route::apiResource('payment-methods', PaymentMethodController::class)->except(['show']);
    Route::apiResource('financial-categories', FinancialCategoryController::class)->except(['show']);
    Route::apiResource('customer-charge-types', CustomerChargeTypeController::class)->except(['show']);
    Route::get('accounting/summary', [AccountingController::class, 'summary']);
    Route::get('accounting/accounts', [AccountingController::class, 'accounts']);
    Route::post('accounting/accounts', [AccountingController::class, 'storeAccount']);
    Route::put('accounting/accounts/{accountingAccount}', [AccountingController::class, 'updateAccount']);
    Route::delete('accounting/accounts/{accountingAccount}', [AccountingController::class, 'destroyAccount']);
    Route::get('accounting/transactions', [AccountingController::class, 'transactions']);
    Route::get('accounting/expenses', [AccountingController::class, 'expenses']);
    Route::post('accounting/transactions', [AccountingController::class, 'storeTransaction']);
    Route::put('accounting/transactions/{accountingTransaction}', [AccountingController::class, 'updateTransaction']);
    Route::delete('accounting/transactions/{accountingTransaction}', [AccountingController::class, 'destroyTransaction']);
    Route::post('accounting/transactions/{accountingTransaction}/review', [AccountingController::class, 'review']);
    Route::post('accounting/transactions/{accountingTransaction}/approve', [AccountingController::class, 'approve']);
    Route::post('accounting/transactions/{accountingTransaction}/reject', [AccountingController::class, 'reject']);
    Route::post('accounting/transactions/{accountingTransaction}/cancel', [AccountingController::class, 'cancel']);
    Route::get('accounting/transactions/{accountingTransaction}/attachment', [AccountingController::class, 'downloadAttachment']);
    Route::get('payroll-runs/eligible-employees', [PayrollController::class, 'eligibleEmployees']);
    Route::post('payroll-runs/generate', [PayrollController::class, 'generate']);
    Route::post('payroll-runs/{payrollRun}/recalculate', [PayrollController::class, 'recalculate']);
    Route::apiResource('payroll-runs', PayrollController::class)->only(['index', 'store', 'show', 'update', 'destroy']);
    Route::post('payroll-runs/{payrollRun}/submit', [PayrollController::class, 'submit']);
    Route::post('payroll-runs/{payrollRun}/review', [PayrollController::class, 'review']);
    Route::post('payroll-runs/{payrollRun}/approve', [PayrollController::class, 'approve']);
    Route::post('payroll-runs/{payrollRun}/reject', [PayrollController::class, 'reject']);
    Route::post('payroll-runs/{payrollRun}/cancel', [PayrollController::class, 'cancel']);
    Route::get('payroll-items/{payrollItem}/payslip', [PayrollController::class, 'payslip']);
    Route::get('payroll-reports/monthly', [PayrollReportController::class, 'monthly']);
    Route::get('payroll-reports/export', [PayrollReportController::class, 'export']);

    Route::get('hr/summary', [EmployeeController::class, 'summary']);
    Route::get('hr/reports', [EmployeeController::class, 'report']);
    Route::get('employees/me', [EmployeeController::class, 'me']);
    Route::apiResource('employees', EmployeeController::class);
    Route::get('hr/structure', [HrStructureController::class, 'index']);
    Route::post('hr/departments', [HrStructureController::class, 'storeDepartment']);
    Route::put('hr/departments/{department}', [HrStructureController::class, 'updateDepartment']);
    Route::delete('hr/departments/{department}', [HrStructureController::class, 'destroyDepartment']);
    Route::post('hr/positions', [HrStructureController::class, 'storePosition']);
    Route::put('hr/positions/{jobPosition}', [HrStructureController::class, 'updatePosition']);
    Route::delete('hr/positions/{jobPosition}', [HrStructureController::class, 'destroyPosition']);
    Route::post('employees/{employee}/documents', [EmployeeDocumentController::class, 'store']);
    Route::get('employee-documents/{employeeDocument}/download', [EmployeeDocumentController::class, 'download']);
    Route::delete('employee-documents/{employeeDocument}', [EmployeeDocumentController::class, 'destroy']);
    Route::get('leave-policies', [LeavePolicyController::class, 'index']);
    Route::post('leave-policies', [LeavePolicyController::class, 'store']);
    Route::put('leave-policies/{leavePolicy}', [LeavePolicyController::class, 'update']);
    Route::delete('leave-policies/{leavePolicy}', [LeavePolicyController::class, 'destroy']);
    Route::post('leave-balances/adjust', [LeavePolicyController::class, 'adjustBalance']);
    Route::get('work-schedules', [WorkScheduleController::class, 'index']);
    Route::post('work-shifts', [WorkScheduleController::class, 'storeShift']);
    Route::put('work-shifts/{workShift}', [WorkScheduleController::class, 'updateShift']);
    Route::delete('work-shifts/{workShift}', [WorkScheduleController::class, 'destroyShift']);
    Route::post('shift-assignments', [WorkScheduleController::class, 'storeAssignment']);
    Route::put('shift-assignments/{employeeShiftAssignment}', [WorkScheduleController::class, 'updateAssignment']);
    Route::delete('shift-assignments/{employeeShiftAssignment}', [WorkScheduleController::class, 'destroyAssignment']);
    Route::post('public-holidays', [WorkScheduleController::class, 'storeHoliday']);
    Route::put('public-holidays/{publicHoliday}', [WorkScheduleController::class, 'updateHoliday']);
    Route::delete('public-holidays/{publicHoliday}', [WorkScheduleController::class, 'destroyHoliday']);
    Route::get('payroll-deductions', [PayrollDeductionController::class, 'index']);
    Route::post('payroll-deduction-rules', [PayrollDeductionController::class, 'storeRule']);
    Route::put('payroll-deduction-rules/{payrollDeductionRule}', [PayrollDeductionController::class, 'updateRule']);
    Route::delete('payroll-deduction-rules/{payrollDeductionRule}', [PayrollDeductionController::class, 'destroyRule']);
    Route::post('employee-payroll-deductions', [PayrollDeductionController::class, 'storeAssignment']);
    Route::put('employee-payroll-deductions/{employeePayrollDeduction}', [PayrollDeductionController::class, 'updateAssignment']);
    Route::delete('employee-payroll-deductions/{employeePayrollDeduction}', [PayrollDeductionController::class, 'destroyAssignment']);
    Route::get('employee-terminations', [EmployeeTerminationController::class, 'index']);
    Route::post('employee-terminations/preview', [EmployeeTerminationController::class, 'preview']);
    Route::post('employee-terminations', [EmployeeTerminationController::class, 'store']);
    Route::post('employee-terminations/{employeeTermination}/review', [EmployeeTerminationController::class, 'review']);
    Route::post('employee-terminations/{employeeTermination}/approve', [EmployeeTerminationController::class, 'approve']);
    Route::post('employee-terminations/{employeeTermination}/reject', [EmployeeTerminationController::class, 'reject']);
    Route::post('employee-terminations/{employeeTermination}/cancel', [EmployeeTerminationController::class, 'cancel']);
    Route::get('biometric-imports', [BiometricAttendanceController::class, 'index']);
    Route::post('biometric-imports', [BiometricAttendanceController::class, 'store']);
    Route::get('biometric-imports/template', [BiometricAttendanceController::class, 'template']);
    Route::get('attendance', [AttendanceController::class, 'index']);
    Route::post('attendance', [AttendanceController::class, 'store']);
    Route::put('attendance/{attendanceRecord}', [AttendanceController::class, 'update']);
    Route::delete('attendance/{attendanceRecord}', [AttendanceController::class, 'destroy']);
    Route::post('attendance/check-in', [AttendanceController::class, 'checkIn']);
    Route::post('attendance/check-out', [AttendanceController::class, 'checkOut']);
    Route::post('attendance/{attendanceRecord}/resolve', [AttendanceController::class, 'resolve']);
    Route::apiResource('leave-requests', LeaveRequestController::class)->only(['index', 'store', 'update']);
    Route::post('leave-requests/{leaveRequest}/resolve', [LeaveRequestController::class, 'resolve']);
    Route::post('leave-requests/{leaveRequest}/cancel', [LeaveRequestController::class, 'cancel']);
    Route::get('leave-requests/{leaveRequest}/attachment', [LeaveRequestController::class, 'download']);
    Route::apiResource('salary-advances', SalaryAdvanceController::class)->only(['index', 'store']);
    Route::post('salary-advances/{salaryAdvance}/review', [SalaryAdvanceController::class, 'review']);
    Route::post('salary-advances/{salaryAdvance}/approve', [SalaryAdvanceController::class, 'approve']);
    Route::post('salary-advances/{salaryAdvance}/reject', [SalaryAdvanceController::class, 'reject']);
    Route::post('salary-advances/{salaryAdvance}/cancel', [SalaryAdvanceController::class, 'cancel']);
    Route::apiResource('employee-adjustments', EmployeeAdjustmentController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::post('employee-adjustments/{employeeAdjustment}/resolve', [EmployeeAdjustmentController::class, 'resolve']);
    Route::post('employees/{employee}/performance-reviews', [PerformanceReviewController::class, 'store']);
    Route::put('performance-reviews/{performanceReview}', [PerformanceReviewController::class, 'update']);
    Route::post('performance-reviews/{performanceReview}/finalize', [PerformanceReviewController::class, 'finalize']);
    Route::delete('performance-reviews/{performanceReview}', [PerformanceReviewController::class, 'destroy']);
    Route::apiResource('shareholders', ShareholderController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::get('shareholder-distributions', [ShareholderDistributionController::class, 'index']);
    Route::post('shareholder-distributions', [ShareholderDistributionController::class, 'store']);
    Route::delete('shareholder-distributions/{shareholderDistribution}', [ShareholderDistributionController::class, 'destroy']);
    Route::post('shareholder-distributions/{shareholderDistribution}/submit', [ShareholderDistributionController::class, 'submit']);
    Route::post('shareholder-distributions/{shareholderDistribution}/review', [ShareholderDistributionController::class, 'review']);
    Route::post('shareholder-distributions/{shareholderDistribution}/approve', [ShareholderDistributionController::class, 'approve']);
    Route::post('shareholder-distributions/{shareholderDistribution}/reject', [ShareholderDistributionController::class, 'reject']);
    Route::post('shareholder-distribution-items/{shareholderDistributionItem}/payments', [ShareholderDistributionController::class, 'pay']);
    Route::apiResource('account-reconciliations', AccountReconciliationController::class)->only(['index', 'store', 'update', 'destroy']);
    Route::post('account-reconciliations/{accountReconciliation}/submit', [AccountReconciliationController::class, 'submit']);
    Route::post('account-reconciliations/{accountReconciliation}/review', [AccountReconciliationController::class, 'review']);
    Route::post('account-reconciliations/{accountReconciliation}/approve', [AccountReconciliationController::class, 'approve']);
    Route::post('account-reconciliations/{accountReconciliation}/reject', [AccountReconciliationController::class, 'reject']);
    Route::get('financial-closings', [FinancialPeriodClosingController::class, 'index']);
    Route::post('financial-closings', [FinancialPeriodClosingController::class, 'store']);
    Route::delete('financial-closings/{financialPeriodClosing}', [FinancialPeriodClosingController::class, 'destroy']);
    Route::post('financial-closings/{financialPeriodClosing}/refresh', [FinancialPeriodClosingController::class, 'refresh']);
    Route::post('financial-closings/{financialPeriodClosing}/submit', [FinancialPeriodClosingController::class, 'submit']);
    Route::post('financial-closings/{financialPeriodClosing}/review', [FinancialPeriodClosingController::class, 'review']);
    Route::post('financial-closings/{financialPeriodClosing}/close', [FinancialPeriodClosingController::class, 'close']);
    Route::post('financial-closings/{financialPeriodClosing}/reject', [FinancialPeriodClosingController::class, 'reject']);
    Route::post('financial-closings/{financialPeriodClosing}/reopen', [FinancialPeriodClosingController::class, 'reopen']);
    Route::get('financial-reports', [FinancialReportController::class, 'index']);
    Route::get('reports/operational', OperationalReportController::class);
    Route::get('authorities/options', [AuthorityController::class, 'options']);
    Route::apiResource('authorities', AuthorityController::class)->except(['show']);
    Route::apiResource('service-areas', ServiceAreaController::class);
    Route::get('customers/collection-options', [CustomerController::class, 'collectionOptions']);
    Route::get('customers/{customer}/photo', [CustomerController::class, 'photo']);
    Route::post('customers/{customer}/photo', [CustomerController::class, 'storePhoto']);
    Route::delete('customers/{customer}/photo', [CustomerController::class, 'destroyPhoto']);
    Route::apiResource('customers', CustomerController::class);
    Route::get('customer-contracts', [CustomerContractController::class, 'index']);
    Route::get('customer-contracts/{customerContract}', [CustomerContractController::class, 'show']);
    Route::post('customers/{customer}/contracts', [CustomerContractController::class, 'store']);
    Route::put('customer-contracts/{customerContract}', [CustomerContractController::class, 'update']);
    Route::post('customer-contracts/{customerContract}/printed', [CustomerContractController::class, 'markPrinted']);
    Route::post('customer-contracts/{customerContract}/confirm', [CustomerContractController::class, 'confirm']);
    Route::get('customer-contracts/{customerContract}/cancellation-preview', [CustomerContractController::class, 'cancellationPreview']);
    Route::post('customer-contracts/{customerContract}/cancel', [CustomerContractController::class, 'cancel']);
    Route::post('contract-cancellation-requests/{contractCancellationRequest}/resolve', [CustomerContractController::class, 'resolveCancellation']);
    Route::get('customer-deposits', [CustomerDepositController::class, 'index']);
    Route::post('customer-deposits/{customerDeposit}/refund', [CustomerDepositController::class, 'refund']);
    Route::get('service-requests/assigned-to-me', [CustomerOperationsController::class, 'assignedToMe']);
    Route::get('customers/{customer}/detail', [CustomerOperationsController::class, 'detail']);
    Route::post('customers/{customer}/charges', [CustomerOperationsController::class, 'storeCharge']);
    Route::post('customers/{customer}/charges/{customerCharge}/cancel', [CustomerOperationsController::class, 'cancelCharge']);
    Route::post('customers/{customer}/service-requests', [CustomerOperationsController::class, 'storeServiceRequest']);
    Route::put('customers/{customer}/service-requests/{customerServiceRequest}', [CustomerOperationsController::class, 'updateServiceRequest']);
    Route::post('customers/{customer}/connection-events', [CustomerOperationsController::class, 'storeConnectionEvent']);
    Route::post('customers/{customer}/agreement/printed', [CustomerController::class, 'markAgreementPrinted']);
    Route::get('customers/{customer}/documents', [CustomerDocumentController::class, 'index']);
    Route::post('customers/{customer}/documents', [CustomerDocumentController::class, 'store']);
    Route::get('customer-documents/{customerDocument}/download', [CustomerDocumentController::class, 'download']);
    Route::delete('customer-documents/{customerDocument}', [CustomerDocumentController::class, 'destroy']);
    Route::post('meters/{meter}/return-to-stock', [MeterController::class, 'returnToStock']);
    Route::apiResource('meters', MeterController::class);
    Route::get('meter-assignments/assigners', [MeterAssignmentController::class, 'assigners']);
    Route::post('meter-assignments/{meterAssignment}/seals', [MeterAssignmentController::class, 'reseal']);
    Route::get('meter-seals/{meterSeal}/photo', [MeterAssignmentController::class, 'downloadSealPhoto']);
    Route::apiResource('meter-assignments', MeterAssignmentController::class);
    Route::apiResource('billing-periods', BillingPeriodController::class);
    Route::apiResource('meter-readings', MeterReadingController::class)->except(['update']);
    Route::apiResource('invoices', InvoiceController::class)->only(['index', 'show']);
    Route::get('payments/receiving-accounts', [PaymentController::class, 'receivingAccounts']);
    Route::apiResource('payments', PaymentController::class)->except(['destroy']);
    Route::apiResource('suppliers', SupplierController::class);

    // Asset Management
    Route::get('assets/stats', [AssetController::class, 'stats']);
    Route::apiResource('assets', AssetController::class);
    Route::get('asset-purchases/{assetPurchase}/attachment', [AssetPurchaseController::class, 'downloadAttachment']);
    Route::apiResource('asset-purchases', AssetPurchaseController::class)
        ->parameters(['asset-purchases' => 'assetPurchase']);
    Route::get('assets-maintenance/upcoming', [AssetMaintenanceController::class, 'upcoming']);
    Route::apiResource('assets-maintenance', AssetMaintenanceController::class)->parameters(['assets-maintenance' => 'maintenance']);

    // Inventory Management
    Route::get('inventory/stats', [InventoryController::class, 'stats']);
    Route::get('inventory/departments', [InventoryController::class, 'departments']);
    Route::get('warehouses', [InventoryController::class, 'warehouses']);
    Route::post('warehouses', [InventoryController::class, 'storeWarehouse']);
    Route::get('warehouses/{warehouse}', [InventoryController::class, 'warehouseDetails']);
    Route::put('warehouses/{warehouse}', [InventoryController::class, 'updateWarehouse']);
    Route::delete('warehouses/{warehouse}', [InventoryController::class, 'destroyWarehouse']);
    Route::get('inventory-items', [InventoryController::class, 'items']);
    Route::post('inventory-items', [InventoryController::class, 'storeItem']);
    Route::put('inventory-items/{item}', [InventoryController::class, 'updateItem']);
    Route::delete('inventory-items/{item}', [InventoryController::class, 'destroyItem']);
    Route::get('inventory-transactions', [InventoryController::class, 'transactions']);
    Route::apiResource('inventory-issues', InventoryIssueController::class)
        ->only(['index', 'show'])
        ->parameters(['inventory-issues' => 'issue']);
    // Goods (Product Catalog)
    Route::apiResource('goods', GoodController::class);

    // Inventory Requests (for approval workflow)
    Route::get('inventory-requests/purchase-accounts', [InventoryRequestController::class, 'purchaseAccounts']);
    Route::apiResource('inventory-requests', InventoryRequestController::class)
        ->only(['index', 'store', 'show']);
    Route::post('inventory-requests/{inventoryRequest}/approve', [InventoryRequestController::class, 'approve']);
    Route::post('inventory-requests/{inventoryRequest}/payments', [InventoryRequestController::class, 'pay']);
});
