[PHP]
engine=On
short_open_tag=Off
precision=14
output_buffering=4096
serialize_precision=-1
zend.enable_gc=On
expose_php=Off
max_execution_time=300
max_input_time=120
memory_limit=512M
error_reporting=E_ALL
display_errors=Off
display_startup_errors=Off
log_errors=On
post_max_size=64M
upload_max_filesize=64M
max_file_uploads=30
default_socket_timeout=60
date.timezone=UTC
extension_dir="ext"
extension=curl
extension=exif
extension=fileinfo
extension=gd
extension=intl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=sodium
extension=zip
curl.cainfo="extras/ssl/cacert.pem"
openssl.cafile="extras/ssl/cacert.pem"

[Session]
session.use_strict_mode=1
session.cookie_httponly=1
session.cookie_samesite=Lax

[opcache]
zend_extension=opcache
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.save_comments=1
